### ISSUE TITLE
Update of dependency spooks causes test failures

### ISSUE THREAD

**Issue by adam-moss** [jared-stilwell/escomplex#26]
Updating dependency spooks from 0.5.x to 2.0.x results in some test failures:

635 passing (819ms)
  61 pending
  6 failing

  1) index: require: array source: core.analyse was given correct asts:
     AssertionError: expected undefined to equal 'esprima.parse result'
      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Context.<anonymous> (test/index.js:143:24)

  2) index: require: array source: correct result was returned:
     AssertionError: expected undefined to equal 'core.analyse result'
      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Context.<anonymous> (test/index.js:161:24)

  3) index: require: string source: core.analyse was given correct ast:
     AssertionError: expected undefined to equal 'esprima.parse result'
      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Context.<anonymous> (test/index.js:231:24)

  4) index: require: string source: correct result was returned:
     AssertionError: expected undefined to equal 'core.analyse result'
      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Context.<anonymous> (test/index.js:243:24)

  5) index: require: string arguments: operators was correct:
     AssertionError: expected undefined to equal 'operators result'
      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Context.<anonymous> (test/traits.js:127:24)

  6) index: require: string arguments: operands was correct:
     AssertionError: expected undefined to equal 'operands result'
      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Context.<anonymous> (test/traits.js:131:24)

**Comment by adam-moss** [comment]
Fixed by #29
